#!/usr/bin/env python3
"""Generate the Python annotation tables from the Swift-Automotive sources.

Swift-Automotive is the canonical home of this data, but it is a private
SwiftPM package and therefore not available when the Python tool is built or
installed. The generated modules are committed instead, and this script is the
tool that refreshes them.

Until the shared annotation data package exists (see Swift-Automotive's
`docs/ANNOTATION_LIBRARY_PLAN.md`), this is the seam that keeps the two
implementations from drifting.

Usage:
    scripts/generate_annotation_tables.py [--swift-automotive PATH]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEFAULT_SWIFT_AUTOMOTIVE = Path.home() / "Documents/late/Automotive-Swift/Swift-Automotive"
DIAGNOSTIC_NAMES_SWIFT = Path(__file__).resolve().parents[3] / "Sources/ecuconnect-tool/DiagnosticNames.swift"
OUTPUT_DIR = Path(__file__).resolve().parent.parent / "ecuconnect_tool" / "annotations"

HEADER = '''"""Generated by scripts/generate_annotation_tables.py — do not edit.

Source: Swift-Automotive ({source})
"""

'''


def parse_strings_file(path: Path) -> dict[str, str]:
    """Parse an Apple .strings file into a plain dict."""
    pattern = re.compile(r'^\s*"([^"]+)"\s*=\s*"(.*)"\s*;\s*$')
    result: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match:
            result[match.group(1)] = match.group(2).replace('\\"', '"')
    return result


def parse_pid_keys(path: Path) -> dict[int, str]:
    """`case 0x0C: return "OBD2_PID_ENGINE_RPM"` → {0x0C: "OBD2_PID_ENGINE_RPM"}."""
    pattern = re.compile(r'case\s+(0x[0-9A-Fa-f]{2}):\s*return\s+"([A-Z0-9_]+)"')
    return {int(m.group(1), 16): m.group(2) for m in pattern.finditer(path.read_text(encoding="utf-8"))}


SPEC_PATTERN = re.compile(
    r'\[(0x[0-9A-Fa-f]{2}),\s*(0x[0-9A-Fa-f]{2})\]:\s*MeasurementSpec\('
    r'.*?mnemonic:\s*"([A-Z0-9_]+)"'
    r'.*?len:\s*(\d+)'
    r'.*?converter:\s*\.([A-Za-z0-9]+)(\([^)]*\))?'
    r'(?:,\s*unit:\s*([A-Za-z0-9.]+))?',
    re.DOTALL,
)


def parse_measurement_specs(path: Path) -> dict[tuple[int, int], dict]:
    """Extract (sid, pid) → {mnemonic, length, converter, argument, unit}."""
    specs: dict[tuple[int, int], dict] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = SPEC_PATTERN.search(line)
        if not match:
            continue
        sid, pid, mnemonic, length, converter, argument, unit = match.groups()
        specs[(int(sid, 16), int(pid, 16))] = {
            "mnemonic": mnemonic,
            "length": int(length),
            "converter": converter,
            "argument": _converter_argument(converter, argument),
            "unit": _unit_symbol(unit),
        }
    return specs


def _converter_argument(converter: str, argument: str | None) -> str | int | None:
    """`.uas(.rotationalFrequency)` → "rotationalFrequency", `.pids(offset: 0x20)` → 0x20."""
    if not argument:
        return None
    inner = argument.strip("()")
    if converter == "uas":
        return inner.lstrip(".").strip()
    if converter == "pids":
        value = inner.split(":")[-1].strip()
        return int(value, 16) if value.startswith("0x") else int(value)
    if converter == "oxygenSensorPositions":
        return inner.split(":")[-1].strip().lstrip(".")
    return None


_UNIT_SYMBOLS = {
    "UnitPressure.kilopascals": "kPa",
    "UnitSpeed.kilometersPerHour": "km/h",
    "UnitLength.kilometers": "km",
    "UnitDuration.seconds": "s",
    "UnitDuration.minutes": "min",
    "UnitTemperature.celsius": "°C",
    "UnitAngle.degrees": "°",
    "UnitElectricPotentialDifference.volts": "V",
    "UnitMassFlow.gramsPerSecond": "g/s",
    "UnitFrequency.hertz": "Hz",
}


def _unit_symbol(unit: str | None) -> str | None:
    if not unit:
        return None
    return _UNIT_SYMBOLS.get(unit, unit.split(".")[-1])


def extract_switch_table(source: str, function: str) -> dict[int, str]:
    """`case 0x22: "Read Data By Identifier"` inside `func <function>` → {0x22: "..."}."""
    start = source.index(f"func {function}(")
    end = source.index("\n    }", source.index("switch", start))
    pattern = re.compile(r'case\s+(0x[0-9A-Fa-f]{2}):\s*"((?:[^"\\]|\\.)*)"')
    return {int(m.group(1), 16): m.group(2) for m in pattern.finditer(source[start:end])}


def extract_dictionary(source: str, name: str) -> dict[int, str]:
    """`0xF190: "VIN",` inside a `let <name>: [UInt16: String] = [ … ]` literal."""
    start = source.index(f"static let {name}")
    end = source.index("\n    ]", start)
    pattern = re.compile(r'(0x[0-9A-Fa-f]{4}):\s*"((?:[^"\\]|\\.)*)"')
    return {int(m.group(1), 16): m.group(2) for m in pattern.finditer(source[start:end])}


def extract_identifier_ranges(source: str) -> list[tuple[int, int, str]]:
    """`case 0xF1A0...0xF1EF: return "Vehicle manufacturer specific"`."""
    start = source.index("func dataIdentifierName(")
    end = source.index("\n    }", source.index("switch", start))
    pattern = re.compile(r'case\s+(0x[0-9A-Fa-f]{4})\.\.\.(0x[0-9A-Fa-f]{4}):\s*return\s+"((?:[^"\\]|\\.)*)"')
    return [(int(m.group(1), 16), int(m.group(2), 16), m.group(3))
            for m in pattern.finditer(source[start:end])]


SUB_FUNCTION_ENUMS = {
    0x10: ("Protocols/UDS/0x10-DiagnosticSessionControl.swift", "DiagnosticSessionType"),
    0x11: ("Protocols/UDS/0x11-ECUReset.swift", "EcuResetType"),
    0x19: ("Protocols/UDS/0x19-ReadDTCInformation.swift", "ReadDTCReportType"),
    0x28: ("Protocols/UDS/0x28-CommunicationControl.swift", "CommunicationControlType"),
    0x31: ("Protocols/UDS/0x31-RoutineControl.swift", "RoutineControlType"),
    0x3E: ("Protocols/UDS/0x3E-TesterPresent.swift", "TesterPresentType"),
    0x85: ("Protocols/UDS/0x85-ControlDTCSetting.swift", "DTCSettingType"),
}


def extract_enum_cases(path: Path, enum: str) -> dict[int, str]:
    """`case programming = 0x02` inside `enum <enum>` → {0x02: "programming"}."""
    source = path.read_text(encoding="utf-8")
    start = source.index(f"enum {enum}")
    end = source.index("\n    }", start)
    pattern = re.compile(r'case\s+`?([A-Za-z0-9_]+)`?\s*=\s*(0x[0-9A-Fa-f]+)')
    return {int(m.group(2), 16): m.group(1) for m in pattern.finditer(source[start:end])}


def render_module(path: Path, source: str, body: str) -> None:
    path.write_text(HEADER.format(source=source) + body, encoding="utf-8")
    print(f"wrote {path.relative_to(Path.cwd()) if path.is_relative_to(Path.cwd()) else path}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--swift-automotive", type=Path, default=DEFAULT_SWIFT_AUTOMOTIVE)
    args = parser.parse_args()

    root = args.swift_automotive
    if not root.is_dir():
        print(f"error: {root} is not a directory", file=sys.stderr)
        return 1

    client = root / "Sources/Swift-Automotive-Client"
    core = root / "Sources/Swift-Automotive-Core"

    # --- PID names -------------------------------------------------------
    pid_keys = parse_pid_keys(client / "OBD2PIDNames.swift")
    client_strings = parse_strings_file(client / "Localizable.strings")
    pid_names = {pid: client_strings[key] for pid, key in sorted(pid_keys.items()) if key in client_strings}
    missing = sorted(set(pid_keys) - set(pid_names))
    if missing:
        print(f"note: {len(missing)} PID keys without a localized name: "
              + ", ".join(f"0x{p:02X}" for p in missing[:8]) + ("…" if len(missing) > 8 else ""))

    body = "PID_NAMES: dict[int, str] = {\n"
    body += "".join(f'    0x{pid:02X}: "{name}",\n' for pid, name in sorted(pid_names.items()))
    body += "}\n"
    render_module(OUTPUT_DIR / "_pid_names.py", "Sources/Swift-Automotive-Client/OBD2PIDNames.swift", body)

    # --- Measurement specs -----------------------------------------------
    specs = parse_measurement_specs(core / "Protocols/OBD2/OBD2+MeasurementSpecs.swift")
    body = "# (service, pid) -> (mnemonic, length, converter, argument, unit)\n"
    body += "MEASUREMENT_SPECS: dict[tuple[int, int], tuple[str, int, str, object, object]] = {\n"
    for (sid, pid), spec in sorted(specs.items()):
        argument = spec["argument"]
        argument_repr = repr(argument) if argument is not None else "None"
        unit_repr = f'"{spec["unit"]}"' if spec["unit"] else "None"
        body += (f'    (0x{sid:02X}, 0x{pid:02X}): ("{spec["mnemonic"]}", {spec["length"]}, '
                 f'"{spec["converter"]}", {argument_repr}, {unit_repr}),\n')
    body += "}\n"
    render_module(OUTPUT_DIR / "_measurement_specs.py",
                  "Sources/Swift-Automotive-Core/Protocols/OBD2/OBD2+MeasurementSpecs.swift", body)

    # --- DTC descriptions and generic fragments ---------------------------
    dtc_descriptions = parse_strings_file(client / "OBD2-DTC.strings")
    core_strings = parse_strings_file(core / "Resources/en.lproj/Localizable.strings")

    body = "DTC_DESCRIPTIONS: dict[str, str] = {\n"
    body += "".join(f'    "{code}": {value!r},\n' for code, value in sorted(dtc_descriptions.items()))
    body += "}\n"
    render_module(OUTPUT_DIR / "_dtc_tables.py", "Sources/Swift-Automotive-Client/OBD2-DTC.strings", body)

    # The localizable strings the `.localized` converter and the DTC fragments resolve against.
    body = "CORE_STRINGS: dict[str, str] = {\n"
    body += "".join(f'    "{key}": {value!r},\n' for key, value in sorted(core_strings.items()))
    body += "}\n"
    render_module(OUTPUT_DIR / "_core_strings.py",
                  "Sources/Swift-Automotive-Core/Resources/en.lproj/Localizable.strings", body)

    # --- Naming tables, shared with the Swift tool -------------------------
    if not DIAGNOSTIC_NAMES_SWIFT.is_file():
        print(f"error: {DIAGNOSTIC_NAMES_SWIFT} not found", file=sys.stderr)
        return 1
    swift = DIAGNOSTIC_NAMES_SWIFT.read_text(encoding="utf-8")

    services = extract_switch_table(swift, "serviceName")
    nrcs = extract_switch_table(swift, "negativeResponseName")
    info_types = extract_switch_table(swift, "vehicleInformationName")
    dids = extract_dictionary(swift, "standardDataIdentifiers")
    did_ranges = extract_identifier_ranges(swift)

    body = "SERVICE_NAMES: dict[int, str] = {\n"
    body += "".join(f'    0x{k:02X}: {v!r},\n' for k, v in sorted(services.items()))
    body += "}\n\nNEGATIVE_RESPONSE_NAMES: dict[int, str] = {\n"
    body += "".join(f'    0x{k:02X}: {v!r},\n' for k, v in sorted(nrcs.items()))
    body += "}\n\nVEHICLE_INFORMATION_NAMES: dict[int, str] = {\n"
    body += "".join(f'    0x{k:02X}: {v!r},\n' for k, v in sorted(info_types.items()))
    body += "}\n\nSTANDARD_DATA_IDENTIFIERS: dict[int, str] = {\n"
    body += "".join(f'    0x{k:04X}: {v!r},\n' for k, v in sorted(dids.items()))
    body += "}\n\n# (first, last, name)\nDATA_IDENTIFIER_RANGES: list[tuple[int, int, str]] = [\n"
    body += "".join(f'    (0x{a:04X}, 0x{b:04X}, {n!r}),\n' for a, b, n in did_ranges)
    body += "]\n"
    render_module(OUTPUT_DIR / "_names.py", "Sources/ecuconnect-tool/DiagnosticNames.swift", body)

    # --- Sub-functions, straight from the UDS enums ------------------------
    sub_functions = {
        service: extract_enum_cases(core / relative, enum)
        for service, (relative, enum) in SUB_FUNCTION_ENUMS.items()
    }
    body = "# service -> sub-function value -> name\nSUB_FUNCTIONS: dict[int, dict[int, str]] = {\n"
    for service, cases in sorted(sub_functions.items()):
        body += f"    0x{service:02X}: {{\n"
        body += "".join(f'        0x{value:02X}: {name!r},\n' for value, name in sorted(cases.items()))
        body += "    },\n"
    body += "}\n"
    render_module(OUTPUT_DIR / "_sub_functions.py", "Sources/Swift-Automotive-Core/Protocols/UDS/", body)
    print(f"{sum(len(c) for c in sub_functions.values())} sub-functions across "
          f"{len(sub_functions)} services")

    print(f"\n{len(pid_names)} PID names, {len(specs)} measurement specs, "
          f"{len(dtc_descriptions)} DTC descriptions, {len(core_strings)} core strings,\n"
          f"{len(services)} services, {len(nrcs)} NRCs, {len(info_types)} info types, "
          f"{len(dids)} DIDs + {len(did_ranges)} DID ranges")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
